name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund
      - name: Lint (skip if no config)
        run: |
          if [ -f package.json ] && (jq -e '.scripts.lint' package.json >/dev/null 2>&1); then npm run lint; else echo 'No lint script'; fi
      - name: Typecheck (skip if no tsconfig)
        run: |
          if [ -f tsconfig.json ]; then npm run typecheck || echo 'No typecheck'; else echo 'No tsconfig'; fi
